"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Task = { id: number; title: string; category: string; xp: number; attribute: string; section: "Principal" | "Diárias" | "Secundárias"; done: boolean; detail: string };
const starterTasks: Task[] = [
  { id: 1, title: "Finalizar apresentação", category: "Projeto", xp: 120, attribute: "+2 Disciplina", section: "Principal", done: false, detail: "até 17:00 · 2 subtarefas" },
  { id: 2, title: "Treino de peito", category: "Academia", xp: 80, attribute: "+2 Força", section: "Diárias", done: false, detail: "18:30" },
  { id: 3, title: "Estudar 40 minutos", category: "Estudos", xp: 60, attribute: "+1 Intelecto", section: "Diárias", done: false, detail: "Matemática" },
  { id: 4, title: "Registrar gastos de ontem", category: "Financeiro", xp: 25, attribute: "+1 Prosperidade", section: "Secundárias", done: false, detail: "sem prazo" },
];
const attributes = [{ icon: "🔥", name: "Disciplina", level: 41, width: 82 }, { icon: "🧠", name: "Intelecto", level: 34, width: 68 }, { icon: "❤️", name: "Vitalidade", level: 31, width: 62 }, { icon: "⚔️", name: "Força", level: 28, width: 56 }];
const nav = [["⌂", "Visão geral"], ["⚔", "Missões"], ["◫", "Jornada"], ["◉", "Hábitos"], ["◒", "Metas & Arcos"], ["✧", "Personagem"], ["◌", "Conquistas"]];

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>(starterTasks); const [xp, setXp] = useState(8420); const [coins, setCoins] = useState(1240); const [modal, setModal] = useState(false); const [toast, setToast] = useState(""); const [tab, setTab] = useState("Visão geral"); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("life-rpg-v1"); if (saved) { const d = JSON.parse(saved); setTasks(d.tasks); setXp(d.xp); setCoins(d.coins); } setHydrated(true); }, []);
  useEffect(() => { if (hydrated) localStorage.setItem("life-rpg-v1", JSON.stringify({ tasks, xp, coins })); }, [tasks, xp, coins, hydrated]);
  const completed = useMemo(() => tasks.filter(t => t.done).length, [tasks]);
  function toggle(id: number) { const item = tasks.find(t => t.id === id); if (!item) return; const done = !item.done; setTasks(old => old.map(t => t.id === id ? { ...t, done } : t)); setXp(x => x + (done ? item.xp : -item.xp)); setCoins(x => x + (done ? 15 : -15)); if (done) { setToast(`⚔ MISSÃO CONCLUÍDA · ${item.title} · +${item.xp} XP`); setTimeout(() => setToast(""), 3200); } }
  function addTask(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const title = String(data.get("title") || "").trim(); if (!title) return; setTasks(t => [...t, { id: Date.now(), title, category: String(data.get("category")), xp: Number(data.get("xp")), attribute: "+1 Disciplina", section: "Secundárias", done: false, detail: "nova missão" }]); setModal(false); }
  return <div className="shell"><aside className="sidebar"><div className="brand"><span>✦</span><div>LIFE RPG<small>SUA VIDA É O JOGO</small></div></div><div className="nav">{nav.map(([icon, label], i) => <button key={label} className={tab === label ? "active" : ""} onClick={() => setTab(label)}><i>{icon}</i>{label}</button>)}</div><div className="nav-label">MÓDULOS — EM BREVE</div><div className="nav muted-nav"><button>⌁ Academia</button><button>▣ Estudos</button><button>◈ Finanças</button></div><div className="user-mini"><div className="avatar"/><div><b>Reinan</b><span>Guerreiro · LV. 27</span></div></div></aside>
    <main><header><div><p className="eyebrow">SÁBADO, 30 DE AGOSTO</p><h1>{tab === "Visão geral" ? "Bom dia, Reinan." : tab}</h1></div><div className="actions"><button className="round">♧</button><button className="round">♢</button><button className="add" onClick={() => setModal(true)}>＋ ADICIONAR</button></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">JORNADA EM ANDAMENTO</p><h2>Um passo real de cada vez.</h2><p>Você já completou {completed} missões hoje. Sua consistência está construindo algo maior.</p><div className="xp"><b>LV. 27</b><div className="meter"><i style={{width: `${Math.min(xp / 100, 100)}%`}}/></div><span>{xp.toLocaleString("pt-BR")} / 10.000 XP</span></div></div><div className="character"/></section>
    <div className="layout"><section className="card missions"><div className="head"><h3>MISSÕES DE HOJE</h3><button>VER TODAS →</button></div>{(["Principal", "Diárias", "Secundárias"] as const).map(section => <div key={section}><p className="cap">MISSÕES {section.toUpperCase()}</p>{tasks.filter(t => t.section === section).map(t => <label className={`mission ${t.done ? "done" : ""}`} key={t.id}><input type="checkbox" checked={t.done} onChange={() => toggle(t.id)}/><span className="mission-copy"><strong>{section === "Principal" && "🔥 "}{t.title}</strong><small>{t.category} · {t.detail}</small></span><span className="reward"><b>+{t.xp} XP</b><small>{t.attribute}</small></span></label>)}</div>)}</section>
      <aside className="right"><section className="card"><div className="head"><h3>SEUS ATRIBUTOS</h3><button>DETALHES</button></div>{attributes.map(a => <div className="attribute" key={a.name}><div><span>{a.icon} {a.name}</span><b>{a.level}</b></div><div className="thin"><i style={{width:`${a.width}%`}}/></div></div>)}<button className="green">VER PERSONAGEM →</button></section><section className="card"><div className="head"><h3>RITMO DA SEMANA</h3><em>🔥 14 dias</em></div><div className="stats"><div><b>{completed}/5</b><span>Missões principais</span></div><div><b>82%</b><span>Hábitos concluídos</span></div><div><b>{coins.toLocaleString("pt-BR")}</b><span>🪙 Life Coins</span></div><div><b>+340</b><span>XP esta semana</span></div></div></section><section className="card"><div className="head"><h3>HÁBITOS</h3><button>VER TODOS</button></div>{[["💧","Beber água","6 de 8 copos","25"],["📖","Ler 20 minutos","Hoje, 21:00","11"],["🌙","Dormir antes das 23h","Hoje","7"]].map(h => <div className="habit" key={h[1]}><i>{h[0]}</i><span><b>{h[1]}</b><small>{h[2]}</small></span><em>🔥 {h[3]}</em></div>)}</section></aside></div></main><nav className="bottom">⌂　 ⚔　 ◫　 ✧　 ☰</nav>{toast && <div className="toast">{toast}</div>}{modal && <div className="overlay" onMouseDown={() => setModal(false)}><form className="modal" onSubmit={addTask} onMouseDown={e => e.stopPropagation()}><button type="button" className="close" onClick={() => setModal(false)}>×</button><h3>NOVA MISSÃO</h3><label>O que você quer concluir?<input name="title" autoFocus placeholder="Ex.: Organizar a semana"/></label><div className="form-row"><label>Categoria<select name="category"><option>Organização</option><option>Estudos</option><option>Academia</option><option>Financeiro</option></select></label><label>XP<select name="xp"><option value="20">20 XP</option><option value="50">50 XP</option><option value="80">80 XP</option></select></label></div><button className="save">ADICIONAR À JORNADA</button></form></div>}</div>;
}
